[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autogen-custom"
version = "0.1.0"
license = {file = "LICENSE-CODE"}
description = "AutoGen custom library for modifying and extending AutoGen's capabilities."
readme = "README.md"
requires-python = ">=3.10, <3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "rich>=13.9.4",
]

[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto --cov=src --cov-report=term-missing --cov-report=xml"
